import { existsSync, readFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { z } from "zod";
import type { Finding } from "./checks/types.js";
import type { ScanResult } from "./scan.js";
import { OperationalError } from "./errors.js";
import { findingId } from "./report/fingerprint.js";

/**
 * Reviewed false positives, kept in a committed `toolprint.ignore.json`.
 *
 * Precision is the whole point of this tool, so there has to be a way to accept
 * one specific finding without lowering `--fail-on` for everything. Two design
 * choices keep that from becoming a way to hide real problems:
 *
 *   - It is a **separate file** from `toolprint.lock`. The lockfile is machine
 *     regenerated by `--update`; a hand-written justification does not belong
 *     somewhere a re-pin will churn it.
 *   - A suppressed finding is still **reported** — it is excluded from the
 *     failure decision, never from the output.
 *
 * Entries are keyed by the stable {@link findingId} already used for SARIF
 * fingerprints and `--baseline`, so there is one identity scheme, not two.
 */

export const IGNORE_FILE_NAME = "toolprint.ignore.json";

const SuppressionSchema = z.object({
  /** Stable finding id, from `--json` output. */
  id: z.string().min(1),
  /** Why this is acceptable. Required — an unexplained suppression is a liability. */
  reason: z.string().min(1),
  /** Optional ISO date (YYYY-MM-DD) after which the suppression stops applying. */
  expires: z.string().optional(),
});

const IgnoreFileSchema = z.object({
  version: z.number().int().optional(),
  ignore: z.array(SuppressionSchema).default([]),
});

export type Suppression = z.infer<typeof SuppressionSchema>;

export interface Suppressions {
  path: string;
  entries: Suppression[];
}

/** Nearest ignore file: an explicit path, else `toolprint.ignore.json` in cwd. */
export function resolveIgnorePath(cwd: string, explicit?: string): string {
  return explicit ? resolve(cwd, explicit) : join(cwd, IGNORE_FILE_NAME);
}

/** Read the ignore file. Absent is normal and yields no entries; malformed is an
 * error, because silently ignoring a broken suppression file would quietly
 * re-enable findings the user believes are handled. */
export function readSuppressions(path: string): Suppressions {
  if (!existsSync(path)) return { path, entries: [] };

  let parsed: unknown;
  try {
    parsed = JSON.parse(readFileSync(path, "utf8"));
  } catch (error) {
    throw new OperationalError(`Ignore file at ${path} is not valid JSON`, error);
  }

  const result = IgnoreFileSchema.safeParse(parsed);
  if (!result.success) {
    throw new OperationalError(
      `Ignore file at ${path} is malformed: ${result.error.issues
        .map((issue) => `${issue.path.join(".")} ${issue.message}`)
        .join("; ")}`,
    );
  }
  return { path, entries: result.data.ignore };
}

function isExpired(entry: Suppression, now: Date): boolean {
  if (!entry.expires) return false;
  const expiry = new Date(`${entry.expires}T23:59:59.999Z`);
  if (Number.isNaN(expiry.getTime())) return false; // unparseable date never suppresses silently
  return now.getTime() > expiry.getTime();
}

export interface SuppressionResult {
  /** All findings, with matched ones marked `suppressed`. Nothing is dropped. */
  findings: Finding[];
  /** Entries whose `expires` has passed — their findings gate again. */
  expired: Suppression[];
  /** Entries that matched nothing this run, so the file can be pruned. */
  unused: Suppression[];
}

/**
 * Mark findings covered by an unexpired suppression. Returns new Finding objects
 * rather than mutating, so callers keep the original scan result intact.
 */
export function applySuppressions(
  findings: Finding[],
  suppressions: Suppressions,
  now: Date = new Date(),
): SuppressionResult {
  const active = new Map<string, Suppression>();
  const expired: Suppression[] = [];
  for (const entry of suppressions.entries) {
    if (isExpired(entry, now)) expired.push(entry);
    else active.set(entry.id, entry);
  }

  const matched = new Set<string>();
  const marked = findings.map((finding) => {
    const id = findingId(finding);
    if (!active.has(id)) return finding;
    matched.add(id);
    return { ...finding, suppressed: true };
  });

  const unused = [...active.values()].filter((entry) => !matched.has(entry.id));
  return { findings: marked, expired, unused };
}

export interface ScanSuppressionResult {
  scan: ScanResult;
  expired: Suppression[];
  unused: Suppression[];
}

/**
 * Apply suppressions across a whole scan. Findings live both on the scan and on
 * each server result, so both are re-marked — otherwise the summary and the
 * per-server view would disagree about what is enforced.
 */
export function applySuppressionsToScan(
  scan: ScanResult,
  suppressions: Suppressions,
  now: Date = new Date(),
): ScanSuppressionResult {
  if (suppressions.entries.length === 0) return { scan, expired: [], unused: [] };

  const overall = applySuppressions(scan.findings, suppressions, now);
  const results = scan.results.map((result) => ({
    ...result,
    findings: applySuppressions(result.findings, suppressions, now).findings,
  }));

  return {
    scan: { ...scan, results, findings: overall.findings },
    expired: overall.expired,
    unused: overall.unused,
  };
}
